IMAGE_FSTYPES += " cpio"
INIT_MANAGER = "sysvinit"
VIRTUAL_RUNTIME_dev_MANAGER = "busybox-mdev"
GLIBC_GENERATE_LOCALES = "en_GB.UTF-8 en_US.UTF-8"
IMAGE_LINGUAS = "en-us"
TCLIBC = "musl"
DISTRO_FEATURES = "pci ipv4 ipv6 usbhost usbgadget wifi"
TMPDIR = "${TOPDIR}/tmp-initramfscfg"
