#!/bin/bash
# swupdate_cert_utils.sh
# Shared utility for SWUpdate CMS signing certificate generation.
# Source this file in SWU generation scripts and call generate_swupdate_cert.
#
# Usage:
#   source swupdate_cert_utils.sh
#   generate_swupdate_cert
#
# Outputs:
#   mycert.cert.pem  - Certificate (used as -signer in openssl cms)
#   mycert.key.pem   - Private key  (used as -inkey  in openssl cms)

generate_swupdate_cert() {
    if [ -f mycert.cert.pem ]; then
        echo "mycert.cert.pem already exists, skipping generation."
        return 0
    fi

    (
        # Generate private key
        openssl genrsa -out mycert.key.pem 4096 && \

        # Generate CSR
        openssl req -new \
            -key mycert.key.pem \
            -out mycert.csr \
            -subj "/O=SWUpdate/CN=target" && \

        # Initialize CA state files
        echo 01 > serial && \
        touch index.txt && \

        # Write CA config
        cat > openssl.cnf <<'OPENSSL_CNF_EOF'
[ ca ]
default_ca = ca_default

[ ca_default ]
database        = index.txt
new_certs_dir   = .
serial          = serial
default_md      = sha256
policy          = policy_any
x509_extensions = v3_cert

[ policy_any ]
commonName           = supplied
organizationName     = supplied

[ v3_cert ]
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid:always, issuer
basicConstraints       = CA:false
keyUsage               = critical, digitalSignature, nonRepudiation
OPENSSL_CNF_EOF

        # Sign certificate with custom validity period
        openssl ca -batch \
            -config openssl.cnf \
            -selfsign \
            -keyfile mycert.key.pem \
            -startdate 20000101000000Z \
            -enddate   20400101000000Z \
            -in  mycert.csr \
            -out mycert.cert.pem && \

        # Cleanup temporary files generated by openssl ca
        rm -f mycert.csr index.txt index.txt.old index.txt.attr \
              serial serial.old openssl.cnf 01.pem

    ) || {
        echo "ERROR: Certificate generation failed." >&2
        rm -f mycert.cert.pem mycert.key.pem
        return 1
    }
}
