EXTRA_OECMAKE = "-DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DNNG_ENABLE_NNGCAT=ON"
TARGET_CFLAGS:apppend = " -fPIC"

ALLOW_EMPTY:${PN} = "1"

RDEPENDS:${PN}-dev = ""
RDEPENDS:${PN}-staticdev = ""