#!/bin/sh

mount_location=$1

factory_dev=`fdisk -lx|grep factory_setting|awk '{print $1}'`
factory_dev_service_name=`echo ${factory_dev}|cut -c2-|sed 's/\//-/'`
home_dev=`fdisk -lx|grep home|awk '{print $1}'`
home_dev_service_name=`echo ${home_dev}|cut -c2-|sed 's/\//-/'`

echo "\
[Unit]
Before=local-fs.target
After=blockdev@${factory_dev_service_name}.target

[Mount]
What=${factory_dev}
Where=/factory_setting" \
        > ${mount_location}/factory_setting.mount

echo "\
[Unit]
Before=local-fs.target
Requires=systemd-fsck@${home_dev_service_name}.service
After=systemd-fsck@${home_dev_service_name}.service
After=blockdev@${home_dev_service_name}.target

[Mount]
What=${home_dev}
Where=/home" \
        > ${mount_location}/home.mount

cd ${mount_location}/local-fs.target.requires
ln -s ../factory_setting.mount factory_setting.mount
ln -s ../home.mount home.mount
