[Service]
# Clear the original ExecStart
ExecStart=
# Set new ExecStart with your custom parameters
ExecStart=/usr/bin/bluealsa --profile=a2dp-source --profile=a2dp-sink --profile=hfp-hf --profile=hsp-hs --profile=hfp-ag --profile=hsp-ag

PrivateUsers=no
PrivateNetwork=no
PrivateDevices=no
ProtectHostname=no