#!/bin/sh

stty erase ^H

AUTO_CONNECT_FILE="/etc/wifi_autoconnect"
USAGE_FILE="/etc/wifi_usage"
SERVICE_MODE=false


# Function to check if a command is successful
check_command() {
    if [ $? -ne 0 ]; then
        echo "Error: $1 failed. Output: $2"
        exit 1
    fi
}

# Function to print messages
message() {
    echo "$1"
}

# Check if running as a service
if [ "$1" = "--service" ]; then
    SERVICE_MODE=true
    echo "Setting the service mode flag"
fi

killall udhcpc 2>/dev/null
killall wpa_supplicant 2>/dev/null

echo "Stopping services managing wlan0..."
systemctl stop wpa_supplicant@wlan0.service 2>/dev/null
systemctl stop systemd-networkd 2>/dev/null
systemctl stop NetworkManager 2>/dev/null
systemctl stop wpa_supplicant 2>/dev/null


rfkill list | awk -F: '/^[0-9]+:.*Wireless LAN/ {print $1}' | while read -r rfkill_id; do

    blocked=$(rfkill list "$rfkill_id" | awk '/Soft blocked:/ {print $3}')
    if [ "$blocked" = "yes" ]; then
        out=$(echo 1 > /sys/class/rfkill/rfkill${rfkill_id}/state 2>&1)
        check_command "echo 1 > /sys/class/rfkill/rfkill${rfkill_id}/state" "$out"
    else
        check_command "skip unblock for rfkill${rfkill_id}" "already unblocked"
    fi
done

# Check the status of wlan_start.service
SERVICE_NAME="wlan_start.service"
SERVICE_STATUS=$(systemctl is-enabled "$SERVICE_NAME" 2>/dev/null)

if [[ "$SERVICE_STATUS" == "disabled" ]]; then
    echo "The $SERVICE_NAME is currently disabled. Enabling it now..."
    systemctl enable "$SERVICE_NAME"
    if [[ $? -eq 0 ]]; then
        echo "$SERVICE_NAME has been successfully enabled."
    else
        echo "Failed to enable $SERVICE_NAME. Please check for issues."
    fi
elif [[ "$SERVICE_STATUS" == "enabled" ]]; then
    echo "$SERVICE_NAME is already enabled. No action required."
else
    echo "$SERVICE_NAME is not found or an error occurred. Please verify the service name."
    exit 1
fi


INTERFACE=$(iw dev | awk '$1=="Interface"{print $2}' | head -n 1)
if [ -z "$INTERFACE" ];  then
        echo "Error: No wireless interface found."
        exit 1
fi

# Bring up the interface
message "Bringing up the interface..."
out=$(ifconfig $INTERFACE up 2>&1)
check_command "ifconfig $INTERFACE up" "$out"

# Create the WPA Supplicant configuration directory if it doesn't exist
message "Creating the WPA Supplicant configuration directory..."
out=$(mkdir -p /etc/wpa_supplicant 2>&1)
check_command "mkdir -p /etc/wpa_supplicant" "$out"

# Check for an auto-connect SSID
AUTO_CONNECT_SSID=""
if [ -f "$AUTO_CONNECT_FILE" ]; then
    echo "Inside the auto_connect_file: $AUTO_CONNECT_FILE"
    TO_CONNECT_CREDENTIALS=$(cat "$AUTO_CONNECT_FILE")
    AUTO_CONNECT_SSID=$(echo "$TO_CONNECT_CREDENTIALS" | cut -d: -f1)
    AUTO_CONNECT_PSK=$(echo "$TO_CONNECT_CREDENTIALS" | cut -d: -f2)
fi

AUTH=$(python3 -c "import sys; sys.path.append('/usr/bin'); from ssid import scan_ssids; d=scan_ssids()[1]; print(d[\"$AUT    O_CONNECT_SSID\"])")
if [ "$SERVICE_MODE" = true ]; then
    # If running as a service, only auto-connect if SSID is configured
    echo "Outer if condition: service mode == true"
    if [ -n "$AUTO_CONNECT_SSID" ]; then
        CONFIG_FILE="/etc/wpa_supplicant/wpa_supplicant-$(iw dev | awk '$1=="Interface"{print $2}' | head -n 1).conf"
        if [ ${#AUTO_CONNECT_PSK} = 0 ]; then
                cat <<EOF > "$CONFIG_FILE"
                 ctrl_interface=/var/run/wpa_supplicant
                 ctrl_interface_group=0
                 update_config=1

                 network={
                     ssid="$AUTO_CONNECT_SSID"
                     key_mgmt=NONE
                     scan_ssid=1
                 }
                EOF
       else
   if [[ "$AUTH" == *"PSK"* ]]; then

              cat <<EOF > "$CONFIG_FILE"
              ctrl_interface=/var/run/wpa_supplicant
              ctrl_interface_group=0
              update_config=1

              network={
                  ssid="$AUTO_CONNECT_SSID"
                  psk=$AUTO_CONNECT_PSK
                  key_mgmt=WPA-PSK
                  scan_ssid=1
              }
               EOF
else
	cat << EOF > "$CONFIG_FILE"
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1

network={
	ssid="$AUTO_CONNECT_SSID"
	psk="$AUTO_CONNECT_PSK"
	key_mgmt=SAE
	scan_ssid=1
	ieee80211w=2
	}
EOF
   fi
        fi
        # Restart network services
        message "Restarting network services..."
        out=$(systemctl restart systemd-networkd.service 2>&1)
        check_command "systemctl restart systemd-networkd.service" "$out"
        out=$(systemctl restart wpa_supplicant@$(iw dev | awk '$1=="Interface"{print $2}' | head -n 1).service 2>&1)
        check_command "systemctl restart wpa_supplicant@<interface>.service" "$out"
        udhcpc -i $INTERFACE
        echo "Auto-connect successful to $AUTO_CONNECT_SSID."
        exit 0
    else
        echo "Service mode: No auto-connect SSID configured. Exiting."
        echo "AUTO_CONNECT_FILE: $AUTO_CONNECT_FILE"
        exit 0
    fi
fi

# Interactive Mode: Display all SSIDs and prompt user
python3 /usr/bin/ssid.py
AVAILABLE_SSIDS=$(python3 -c "import sys; sys.path.append('/usr/bin'); from ssid import scan_ssids; li = scan_ssids()[0]; print('\n'.join(li))")

echo "Available Networks:"
echo "$AVAILABLE_SSIDS"

# Prompt user for SSID and password
read -p "Enter your Wi-Fi SSID: " SSID
read -sp "Enter your Wi-Fi password (leave empty for open Auth Networks): " PASSWORD
echo

# Validate SSID input
if [ -z "$SSID" ]; then
    echo "Error: SSID cannot be empty."
    exit 1
fi


AUTH=$(python3 -c "import sys; sys.path.append('/usr/bin'); from ssid import scan_ssids; d=scan_ssids()[1]; print(d[\"$SSID\"])")
# Prompt for enabling auto-connect
read -p "Do you want to enable auto-connect for $SSID? (yes/no): " AUTOCONNECT_CHOICE

# Create WPA Supplicant configuration file
CONFIG_FILE="/etc/wpa_supplicant/wpa_supplicant-$(iw dev | awk '$1=="Interface"{print $2}' | head -n 1).conf"

if [ -n "$PASSWORD" ]; then
    # Generate the WPA Pre-shared Key (PSK) using wpa_passphrase
    WPA_OUTPUT=$(wpa_passphrase "$SSID" "$PASSWORD")
    check_command "wpa_passphrase generation"

    PSK=$(echo "$WPA_OUTPUT" | sed -n '/^\s*psk=/s/.*psk=//p' | tail -n 1)
    if [ -z "$PSK" ]; then
        echo "Error: Failed to extract PSK."
        exit 1
    fi

#Auto-connect Save the PSK to a file
if [[ "$AUTOCONNECT_CHOICE" == "yes" || "$AUTOCONNECT_CHOICE" == "y" ]]; then
            if [[ *"$AUTH"* == "PSK" ]]; then
    echo "$SSID:$PSK" > "$AUTO_CONNECT_FILE"
            else
                echo "$SSID:$PASSWORD" > "$AUTO_CONNECT_FILE"

    echo "Auto-connect enabled for SSID: $SSID."
            fi
else
    echo "Auto-connect disabled."
fi
   if [[ "$AUTH" == *"PSK"* ]]; then

    cat <<EOF > "$CONFIG_FILE"
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1

network={
    ssid="$SSID"
    psk=$PSK
    key_mgmt=WPA-PSK
    scan_ssid=1
}
EOF
else
	cat << EOF > "$CONFIG_FILE"
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1

network={
	ssid="$SSID"
	psk="$PASSWORD"
	key_mgmt=SAE
	scan_ssid=1
	ieee80211w=2
	}
EOF
   fi
else
# Create WPA Supplicant configuration file for open networks
    cat <<EOF > "$CONFIG_FILE"
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1

network={
    ssid="$SSID"
    key_mgmt=NONE
    scan_ssid=1
}
EOF
fi

# Prompt user to review and edit the file
echo "Configuration file created at $CONFIG_FILE."
read -p "Do you want to edit the file before applying? (y/n): " EDIT_CHOICE
if [[ "$EDIT_CHOICE" == "y" || "$EDIT_CHOICE" == "Y" ]]; then
    # Open the file with vi editor
    vi "$CONFIG_FILE"
    cat $CONFIG_FILE
    echo "Please review your changes. Press Enter to continue."
    read
fi

# Update connection frequency
USAGE_FILE="/etc/.wifi_usage"
SSID_CONNECTED="$SSID"
#echo "USAGE FILE: $USAGE_FILE"

if [ -f "$USAGE_FILE" ]; then
    usage=$(cat "$USAGE_FILE")
else
    usage="{}"
fi

# Increment the frequency for the connected SSID
updated_usage=$(python3 -c "
import json
usage = json.loads('''$usage''')
usage['$SSID_CONNECTED'] = usage.get('$SSID_CONNECTED', 0) + 1
print(json.dumps(usage))
")

echo "$updated_usage" > "$USAGE_FILE"

# Configure systemd-networkd to use DHCP for the interface
message "Creating the systemd network configuration for $INTERFACE ..."
out=$(cat <<EOF > /etc/systemd/network/25-wlan.network
[Match]
Name=$INTERFACE

[Network]
DHCP=ipv4
EOF
2>&1)
check_command "Creating systemd network configuration" "$out"

# Restart the wpa_supplicant service
out=$(systemctl restart systemd-networkd.service 2>&1)
check_command "systemctl restart systemd-networkd.service" "$out"
out=$(systemctl restart wpa_supplicant@wlan0.service 2>&1)
check_command "systemctl restart wpa_supplicant@wlan0.service" "$out"

RETRIES=0
while [[ $(iw dev $INTERFACE link) == *"Not connected."* ]]; do
    if [ $RETRIES -ge 5 ]; then
        echo "Error: Failed to connect to the network after multiple attempts."
        exit 1
    fi
    echo "Waiting for network connection....."
    sleep 3
    RETRIES=$((RETRIES +1))
done

sleep 12
udhcpc -i $INTERFACE
echo "Successfully connected to the network. "
iw dev $INTERFACE link
