# Main NetworkManager configuration
[main]
# Enables support for both ifupdown (legacy) and keyfile (modern NM connections)
plugins=ifupdown,keyfile

# Configuration for legacy ifupdown-managed network interfaces
[ifupdown]
# Allows NetworkManager to control interfaces defined in /etc/network/interfaces
managed=false

[logging]
#OFF, ERR, WARN, INFO, DEBUG
level=ERR

# NONE --> domain-specific logs.
# ALL  --> Logs everything.
# CORE --> Logs core NetworkManager operations.
# DEVICE --> Logs network devices (e.g., wlan0, eth0).
# WIRELESS --> Logs Wi-Fi events.
# SECURITY --> Logs authentication details (WPA, encryption failures).
# DHCP --> Logs DHCP client and server messages.
# IP4 / IP6 --> Logs IPv4 and IPv6 assignments.
# AUTOIP --> Logs auto-IP configurations.
# VPN --> Logs VPN-related events.
domains=ALL
